"""add motor fields to quote & policy

Revision ID: 13c2128081b6
Revises: 
Create Date: 2025-08-24 09:52:11.042196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c2128081b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    def add_column_if_missing(table: str, column: sa.Column) -> None:
        existing = {c['name'] for c in inspector.get_columns(table)}
        if column.name not in existing:
            op.add_column(table, column)

    # Policies: add columns (nullable=True to satisfy SQLite ADD COLUMN)
    add_column_if_missing('policies', sa.Column('vehicle_category', sa.String(length=20), nullable=True))
    add_column_if_missing('policies', sa.Column('cover_type', sa.String(length=20), nullable=True))
    add_column_if_missing('policies', sa.Column('add_ons', sa.JSON(), nullable=True))
    add_column_if_missing('policies', sa.Column('term_months', sa.Integer(), nullable=True, server_default=sa.text("12")))
    add_column_if_missing('policies', sa.Column('kyc_status', sa.String(length=20), nullable=True, server_default=sa.text("'pending'")))
    add_column_if_missing('policies', sa.Column('valuation_required', sa.Boolean(), nullable=True, server_default=sa.text("0")))
    add_column_if_missing('policies', sa.Column('mechanical_assessment_required', sa.Boolean(), nullable=True, server_default=sa.text("0")))

    # Quotes: add columns
    add_column_if_missing('quotes', sa.Column('vehicle_category', sa.String(length=20), nullable=True))
    add_column_if_missing('quotes', sa.Column('cover_type', sa.String(length=20), nullable=True))
    add_column_if_missing('quotes', sa.Column('add_ons', sa.JSON(), nullable=True))
    add_column_if_missing('quotes', sa.Column('term_months', sa.Integer(), nullable=True, server_default=sa.text("12")))
    add_column_if_missing('quotes', sa.Column('kyc_status', sa.String(length=20), nullable=True, server_default=sa.text("'pending'")))
    add_column_if_missing('quotes', sa.Column('valuation_required', sa.Boolean(), nullable=True, server_default=sa.text("0")))
    add_column_if_missing('quotes', sa.Column('mechanical_assessment_required', sa.Boolean(), nullable=True, server_default=sa.text("0")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('mechanical_assessment_required')
        batch_op.drop_column('valuation_required')
        batch_op.drop_column('kyc_status')
        batch_op.drop_column('term_months')
        batch_op.drop_column('add_ons')
        batch_op.drop_column('cover_type')
        batch_op.drop_column('vehicle_category')

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_column('mechanical_assessment_required')
        batch_op.drop_column('valuation_required')
        batch_op.drop_column('kyc_status')
        batch_op.drop_column('term_months')
        batch_op.drop_column('add_ons')
        batch_op.drop_column('cover_type')
        batch_op.drop_column('vehicle_category')

    # ### end Alembic commands ###
